version: 2
jobs:
  build:
    docker:
      - image: python:3.6

    steps:
      - checkout

      - restore_cache:
          key: pipenv-{{ .Branch  }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: Install pipenv
          command: pip install pipenv

      - run:
          name: Install requirements libs
          command: pipenv install

      - save_cache:
          key: pipenv-{{ .Branch  }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local/share/virtualenvs

  send_mail:
    docker:
      - image: python:3.6
    steps:
      - attache_workspace:
          at: .

      - run:
          name: Send mail by send_mail.py
          command: pipenv run python send_mail.py

workflows:
  version: 2
  send_mail:
    jobs:
      - build

      - send_mail:
          requires:
            - build
